apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghostbusters-orchestrator
  namespace: ghostbusters-ai
  labels:
    app: ghostbusters-orchestrator
    component: core
    version: v1.0.0
spec:
  replicas: 1  # Start with 1 replica for cost control
  selector:
    matchLabels:
      app: ghostbusters-orchestrator
  template:
    metadata:
      labels:
        app: ghostbusters-orchestrator
        component: core
        version: v1.0.0
    spec:
      containers:
      - name: orchestrator
        image: gcr.io/aardvark-linkedin-grepper/ghostbusters-orchestrator:v1.0.0
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 9090
          name: metrics
        env:
        - name: ENVIRONMENT
          value: "development"
        - name: LOG_LEVEL
          value: "INFO"
        - name: COST_MONITORING_ENABLED
          value: "true"
        - name: MAX_CONCURRENT_ANALYSES
          value: "5"
        resources:
          requests:
            memory: "256Mi"    # Conservative resource requests
            cpu: "200m"
          limits:
            memory: "512Mi"    # Reasonable resource limits
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: config
          mountPath: /app/config
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: config
        configMap:
          name: ghostbusters-config
      - name: logs
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: ghostbusters-orchestrator
  namespace: ghostbusters-ai
  labels:
    app: ghostbusters-orchestrator
    component: core
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  - port: 9090
    targetPort: 9090
    name: metrics
  selector:
    app: ghostbusters-orchestrator
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ghostbusters-orchestrator-hpa
  namespace: ghostbusters-ai
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ghostbusters-orchestrator
  minReplicas: 1      # Conservative scaling for cost control
  maxReplicas: 3      # Max 3 replicas during development
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80  # Scale up at 80% CPU
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 85  # Scale up at 85% memory
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300  # 5 minutes to prevent rapid scaling
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
